[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/API/Booking"
  to = "/.netlify/functions/booking"
  status = 200

[[redirects]]
  from = "/api/booking"
  to = "/.netlify/functions/booking"
  status = 200
